"""
# Feature: export-gate-and-preview-fidelity, Property 68: Lint and format judge hand-written code, and state the bar

Property 68 states that every lint and format finding refers to a hand-written
file; that the excluded set comes from a single definition shared by the
``Quality_Gate``, the ``lint`` stage, and the packaging exclusion; that a tree whose
only defects lie in generated files reports ``lint`` passed with ``formatted`` and
``lint_clean`` met; that a genuine hand-written defect is still reported; and that
every result names the profile applied, its source, and the line length.

The defect this closes: the lint stage blocked an export on fourteen findings, none
of them in a file the plugin's author is permitted to edit -- generated
``__init__.py`` and ``schema.py`` emitted by the CLI from the spec, which the
``Agent_Rulebook`` forbids touching and ``insight-plugin refresh`` would overwrite.
Real, correctly located, and unfixable by their audience.

**The linter and the formatter are stubbed, deliberately.** The property is about
*which files are judged and what is reported*, not about prospector's own analysis:
a stub that reports exactly the defects the generator planted makes the file
partition the only variable, and lets the claim be quantified over a hundred
arrangements instead of the handful a real tree happens to contain. The real
toolchain is exercised against real trees by the example-based checks in
``test_export_gate_bug_conditions.py`` and by the integration suite (task 12).

**Validates: Requirements 2.6, 2.7, 2.8, 2.9** -- also preserves 3.3, 3.7
"""

import asyncio
import json
from pathlib import Path
from typing import Dict, Tuple

from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from icplugin_builder.core.plugin_files import (
    hand_written_python,
    is_generated,
    is_lint_excluded,
    is_packaging_excluded,
)
from icplugin_builder.integrations.build_prep import PLUGIN_LINE_LENGTH, LintProfile
from icplugin_builder.integrations.code_validator import CodeValidator, StageName, StageStatus
from icplugin_builder.integrations.definition_of_done import (
    CONDITION_FORMATTED,
    CONDITION_LINT_CLEAN,
    ConditionStatus,
    evaluate_done,
)
from icplugin_builder.integrations.quality_gate import SOURCE_FORMAT, SOURCE_PROSPECTOR, QualityGate

PACKAGE = "icon_property"

#: Where a planted defect can live, and what each placement means for the checks.
#: ``lint_judged`` and ``format_judged`` are the answers the single shared
#: definition gives, stated here so the property compares against the rulebook's
#: reason rather than against the implementation's behaviour.
PLACEMENTS: Dict[str, Dict[str, object]] = {
    # Hand-written plugin code: judged by everything.
    "hand_written": {"path": f"{PACKAGE}/util/api.py", "lint_judged": True, "format_judged": True},
    "hand_written_action": {
        "path": f"{PACKAGE}/actions/get_thing/action.py",
        "lint_judged": True,
        "format_judged": True,
    },
    # Generated by the CLI: judged by neither, still packaged.
    "generated_schema": {
        "path": f"{PACKAGE}/actions/get_thing/schema.py",
        "lint_judged": False,
        "format_judged": False,
    },
    "generated_init": {"path": f"{PACKAGE}/__init__.py", "lint_judged": False, "format_judged": False},
    "generated_setup": {"path": "setup.py", "lint_judged": False, "format_judged": False},
    # The unit tests: not linted, still compiled, formatted and run (3.7).
    "unit_test": {"path": "unit_test/test_api.py", "lint_judged": False, "format_judged": True},
}

#: A stub linter/formatter reports the paths named in this file, intersected with
#: the file list it is given. Written beside the tree rather than passed as an
#: argument because the gate builds both commands itself.
MANIFEST = "planted-defects.json"


def _write_stubs(root: Path) -> Tuple[str, str]:
    """Write a stub ``prospector`` and ``black`` that report the planted defects.

    Both read the manifest and answer only about paths they were actually asked
    to judge -- which is what makes "the check never saw a generated file" and "the
    check saw it and ignored it" distinguishable outcomes.
    """
    prospector = root / "stub-prospector"
    prospector.write_text(
        "#!/usr/bin/env python3\n"
        "import json, os, sys\n"
        f"planted = json.load(open(os.path.join(os.getcwd(), {MANIFEST!r})))\n"
        "print(json.dumps({'messages': [\n"
        "    {'location': {'path': path, 'line': 3}, 'code': 'undefined-variable',\n"
        "     'message': 'planted defect'} for path in planted]}))\n",
        encoding="utf-8",
    )
    prospector.chmod(0o755)

    black = root / "stub-black"
    black.write_text(
        "#!/usr/bin/env python3\n"
        "import json, os, sys\n"
        f"planted = set(json.load(open(os.path.join(os.getcwd(), {MANIFEST!r}))))\n"
        "given = [arg for arg in sys.argv[1:] if not arg.startswith('-')]\n"
        "named = [path for path in given if path in planted]\n"
        "for path in named:\n"
        "    sys.stderr.write(f'would reformat {path}\\n')\n"
        "sys.exit(1 if named else 0)\n",
        encoding="utf-8",
    )
    black.chmod(0o755)
    return str(prospector), str(black)


def _build_tree(root: Path, planted: Tuple[str, ...]) -> Tuple[str, str, LintProfile]:
    """Materialize a plugin tree, plant ``planted``'s defects, and pin the bar."""
    for placement in PLACEMENTS.values():
        target = root / str(placement["path"])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("x = 1\n", encoding="utf-8")
    (root / MANIFEST).write_text(
        json.dumps([str(PLACEMENTS[name]["path"]) for name in planted]),
        encoding="utf-8",
    )
    profile = root / "pinned.yaml"
    profile.write_text("strictness: veryhigh\n", encoding="utf-8")
    prospector, black = _write_stubs(root)
    return prospector, black, LintProfile(path=str(profile), source="repository", detail="pinned by the property")


def _expected(planted: Tuple[str, ...], key: str) -> Tuple[str, ...]:
    """The planted paths the check named by ``key`` is supposed to judge."""
    return tuple(sorted(str(PLACEMENTS[name]["path"]) for name in planted if PLACEMENTS[name][key]))


_SETTINGS = settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
)

_PLANTINGS = st.lists(st.sampled_from(sorted(PLACEMENTS)), min_size=0, max_size=len(PLACEMENTS), unique=True).map(tuple)


@given(planted=_PLANTINGS)
@_SETTINGS
def test_every_lint_and_format_finding_refers_to_a_hand_written_file(tmp_path_factory, planted):
    """Claims 1 and 4: only judged files are reported, and they *are* reported."""
    root = tmp_path_factory.mktemp("bar")
    prospector, black, profile = _build_tree(root, planted)
    gate = QualityGate(run_tests=False, prospector_executable=prospector, black_executable=black, lint_profile=profile)
    report = asyncio.run(gate.run(root))

    lint_paths = tuple(sorted(finding.path for finding in report.by_source(SOURCE_PROSPECTOR)))
    format_paths = tuple(sorted(finding.path for finding in report.by_source(SOURCE_FORMAT)))

    for path in lint_paths + format_paths:
        assert not is_generated(path), f"{path} is generated and its author may not edit it, yet it is reported"
    for path in lint_paths:
        assert not is_lint_excluded(path), f"{path} is outside the linter's remit, yet the linter reported it"

    assert lint_paths == _expected(planted, "lint_judged"), (
        "the lint findings are not exactly the planted defects in lint-judged files, so either a defect the "
        f"author must fix went unreported or one they may not fix was reported: {lint_paths}"
    )
    assert format_paths == _expected(
        planted, "format_judged"
    ), f"the format findings are not exactly the planted defects in format-judged files: {format_paths}"


@given(planted=_PLANTINGS)
@_SETTINGS
def test_the_excluded_set_comes_from_one_definition_and_packaging_is_not_it(tmp_path_factory, planted):
    """Claim 2: one definition, three consumers -- and packaging still ships them.

    The three predicates disagree on purpose. Collapsing them would be the real
    bug: a generated ``schema.py`` is excluded from lint and **must** be packaged,
    because the plugin cannot run without it.
    """
    root = tmp_path_factory.mktemp("bar")
    _build_tree(root, planted)

    judged = hand_written_python(root)
    for placement in PLACEMENTS.values():
        path = str(placement["path"])
        assert (path in judged) is not is_generated(path), f"{path} is judged iff it is not generated"
        if not is_generated(path):
            assert not is_packaging_excluded(path), f"{path} is hand-written yet excluded from the artifact"
        else:
            assert not is_packaging_excluded(path), f"{path} is generated and must still be packaged"


@given(
    planted=st.lists(st.sampled_from(["generated_schema", "generated_init", "generated_setup"]), unique=True).map(tuple)
)
@_SETTINGS
def test_a_tree_whose_only_defects_are_generated_clears_lint_and_format(tmp_path_factory, planted):
    """Claim 3: the plugin a reviewer would call clean is reported clean."""
    root = tmp_path_factory.mktemp("bar")
    prospector, black, profile = _build_tree(root, planted)
    gate = QualityGate(run_tests=False, prospector_executable=prospector, black_executable=black, lint_profile=profile)
    report = asyncio.run(gate.run(root))
    done = evaluate_done(root, quality_report=report)

    assert report.by_source(SOURCE_PROSPECTOR) == (), report.render()
    assert report.by_source(SOURCE_FORMAT) == (), report.render()
    for name in (CONDITION_LINT_CLEAN, CONDITION_FORMATTED):
        condition = next(item for item in done.conditions if item.name == name)
        assert condition.status is ConditionStatus.MET, f"{name} is {condition.status.value}: {condition.detail}"

    validator = CodeValidator(prospector_executable=prospector, lint_profile=profile)
    spec = next(item for item in validator._stage_specs("tag", root) if item.name == StageName.LINT)
    stage = asyncio.run(validator._run_stage(spec, root))
    assert stage.status is StageStatus.PASSED, f"{stage.status.value}: {stage.message}"


@given(planted=_PLANTINGS)
@_SETTINGS
def test_the_lint_stage_and_the_gate_never_disagree_about_one_tree(tmp_path_factory, planted):
    """Claim 2 from the other side: one definition means one verdict.

    The stage used to run a different linter under different rules, so the two
    could reach opposite conclusions about the same plugin -- the same
    two-subsystems-disagree shape as the unit tests in clause 2.4.
    """
    root = tmp_path_factory.mktemp("bar")
    prospector, black, profile = _build_tree(root, planted)
    gate = QualityGate(run_tests=False, prospector_executable=prospector, black_executable=black, lint_profile=profile)
    report = asyncio.run(gate.run(root))

    validator = CodeValidator(prospector_executable=prospector, lint_profile=profile)
    spec = next(item for item in validator._stage_specs("tag", root) if item.name == StageName.LINT)
    stage = asyncio.run(validator._run_stage(spec, root))

    gate_clean = report.by_source(SOURCE_PROSPECTOR) == ()
    assert stage.passed is gate_clean, (
        f"the stage says {stage.status.value} and the gate reports "
        f"{len(report.by_source(SOURCE_PROSPECTOR))} lint finding(s) for one tree: {stage.message}"
    )


@given(planted=_PLANTINGS)
@_SETTINGS
def test_every_result_names_the_profile_its_source_and_the_width(tmp_path_factory, planted):
    """Claim 5: a finding is attributable to the bar that produced it."""
    root = tmp_path_factory.mktemp("bar")
    prospector, black, profile = _build_tree(root, planted)
    gate = QualityGate(run_tests=False, prospector_executable=prospector, black_executable=black, lint_profile=profile)
    report = asyncio.run(gate.run(root))

    assert report.lint_profile is profile
    assert report.line_length == PLUGIN_LINE_LENGTH
    surface = "\n".join((report.summary(), report.bar()))
    for token in (str(profile.path), str(profile.source), str(PLUGIN_LINE_LENGTH)):
        assert token in surface, f"the report does not name {token!r}: {surface!r}"

    validator = CodeValidator(prospector_executable=prospector, lint_profile=profile)
    spec = next(item for item in validator._stage_specs("tag", root) if item.name == StageName.LINT)
    stage = asyncio.run(validator._run_stage(spec, root))
    assert stage.lint_profile is profile
    assert stage.line_length == PLUGIN_LINE_LENGTH
    for token in (str(profile.path), str(profile.source), str(PLUGIN_LINE_LENGTH)):
        assert token in stage.message, f"the stage result does not name {token!r}: {stage.message!r}"
