"""The Kiro agent config the plugin-implementation work is delegated to.

The Kiro CLI can run as an *agent* -- reading files, writing files, and running
commands until a task is done -- rather than as a single-shot text completion.
Doing the plugin implementation that way is the point of this module: it builds
the agent configuration that gives the delegated CLI the tool access it needs and
points it at the operator's own InsightConnect plugin skills and steering as its
rulebook.

**The skills are the rulebook; this module does not restate them.** The
authoritative rules for how an InsightConnect plugin is written live in the
operator's Kiro skills and steering (``plugin-dev``, ``create-new-plugin``,
``implementation``, ``common-mistakes``, ``plugin-spec``, ``testing``, ...). They
are referenced here as agent ``resources`` so the agent loads the real files. A
paraphrase maintained inside this codebase would drift from them and then
contradict them, which has already happened once in this project's history. The
only prose this module contributes is the *task framing* and the *definition of
done* -- neither of which the skills specify, because they describe how a human
works in an IDE rather than what this tool must guarantee before it reports
success.

Config layout and discovery follow the documented Kiro conventions (see the
``agentic-harness-conventions`` steering): a named agent is a JSON file in
``$KIRO_HOME/agents/<name>.json`` (``KIRO_HOME`` defaulting to ``~/.kiro``), and
is then selectable with ``kiro-cli chat --agent <name>``. Writing the config
there rather than into the plugin's own working tree keeps it out of the
generated plugin and therefore out of the ``.plg`` artifact.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional, Sequence, Tuple

__all__ = [
    "AGENT_NAME",
    "GENERATED_MARKER",
    "RULEBOOK_FILES",
    "BUNDLED_RULEBOOK_DIR",
    "rulebook_resource",
    "default_skill_resources",
    "DEFAULT_TOOLS",
    "AgentConfigError",
    "AgentConfig",
    "default_agent_config",
    "resolve_kiro_home",
    "agent_config_path",
    "write_agent_config",
    "missing_resources",
]

#: The agent name this tool registers and selects with ``--agent``.
AGENT_NAME = "icplugin-builder"

#: Marker stored in the generated config's description so a later write can tell
#: its own file apart from one the operator hand-authored at the same path.
GENERATED_MARKER = "[generated by insightconnect-plugin-builder]"


def resolve_kiro_home() -> Path:
    """Resolve the Kiro user configuration directory.

    Honors the ``KIRO_HOME`` override before falling back to ``~/.kiro``, per the
    ``agentic-harness-conventions`` steering.

    Returns:
        The resolved Kiro home directory (not necessarily existing).
    """
    override = os.environ.get("KIRO_HOME")
    if override:
        return Path(override).expanduser()
    return Path("~/.kiro").expanduser()


#: The rulebook's filenames, relative to a skills/steering root. One list, used
#: both to resolve what the agent loads and to check the bundled copy is complete.
RULEBOOK_FILES: Tuple[str, ...] = (
    "skills/plugin-dev.md",
    "skills/plugin-build-prep.md",
    "skills/create-new-plugin.md",
    "skills/create-plugin-action.md",
    "steering/plugin-spec.md",
    "steering/implementation.md",
    "steering/common-mistakes.md",
    "steering/testing.md",
    "steering/structure.md",
    "steering/exceptions.md",
    "steering/prospector.md",
)

#: The rulebook bundled with this package, used when the operator has no copy of
#: their own. Ships in the wheel via ``[tool.setuptools.package-data]``.
BUNDLED_RULEBOOK_DIR: Path = Path(__file__).resolve().parent.parent / "rulebook"


def rulebook_resource(relative: str) -> Optional[str]:
    """Resolve one rulebook file, preferring the operator's copy over the bundled one.

    Order matters and is deliberate:

    1. ``~/.kiro/<relative>`` -- the operator's own rulebook. It wins because
       editing those files is how the tool's behaviour is meant to be changed, and
       a bundled copy silently overriding a local edit would be the worst outcome.
    2. The copy bundled with this package, so an operator who has never installed
       the plugin skills still gets a full rulebook rather than a degraded agent.

    Returns ``None`` when neither exists, which the caller drops from the resource
    list rather than failing on.
    """
    operator_copy = resolve_kiro_home() / relative
    if operator_copy.is_file():
        return str(operator_copy)
    bundled = BUNDLED_RULEBOOK_DIR / relative
    if bundled.is_file():
        return str(bundled)
    return None


def default_skill_resources() -> Tuple[str, ...]:
    """The rulebook the agent loads: the operator's files, else the bundled ones.

    Absolute paths rather than the ``~``-relative strings this used to hold. Both
    candidate roots are known here, so resolving at config-write time is clearer
    than emitting a path that may or may not exist and letting the CLI silently
    skip it.

    The plugin conventions live in these files rather than in this codebase, so the
    agent loads the real thing instead of a paraphrase (see
    ``.kiro/steering/project-conventions.md``). The bundled copy exists because the
    files were previously required from ``~/.kiro`` and are in no public
    repository, so a new user had no way to obtain them and got a materially worse
    agent with no way to fix it.

    A file present in neither place is dropped rather than failing the run: an
    operator missing one skill still gets a working agent, just less guidance.
    """
    resolved = (rulebook_resource(relative) for relative in RULEBOOK_FILES)
    return tuple(path for path in resolved if path is not None)


#: The tools the agent is given. This is narrower than the CLI's full set: it
#: covers reading and writing the plugin tree, searching it, and running the
#: toolchain (``insight-plugin``, ``prospector``, ``black``, ``pytest``,
#: ``docker``). Deliberately excluded are ``aws``, ``delegate``, ``knowledge``,
#: ``report``, and ``introspect`` -- none are needed to build a plugin, and each
#: would widen what a prompt-injected instruction could reach.
#:
#: ``shell`` **is** required: the plugin workflow is defined in terms of running
#: ``insight-plugin create``/``refresh``/``validate`` and the linters, and an
#: agent without it cannot complete or verify its own work.
DEFAULT_TOOLS: Tuple[str, ...] = ("read", "write", "shell", "grep", "glob")

#: The standing system prompt. Task framing and the done bar only -- the plugin
#: rules come from the referenced skills, not from here.
_SYSTEM_PROMPT = """\
You are implementing a Rapid7 InsightConnect plugin. You are working directly in \
the plugin's project directory and you have read, write, and shell access to it.

Your rulebook is the InsightConnect plugin skills and steering loaded into your \
context. Follow them. Where they specify a workflow (for example: edit \
plugin.spec.yaml first, then run insight-plugin refresh, never hand-edit \
generated files), follow that workflow rather than writing the derived files \
yourself.

`plugin.spec.yaml` is the source of truth for what to build. It may be \
incomplete or invalid -- if so, correct it to satisfy both the plugin \
specification and the spec rules in your steering, then regenerate from it.

Work until the plugin is genuinely finished, verifying as you go. Finished means \
all of the following:

- `insight-plugin validate` passes.
- The linter your steering specifies is clean.
- Every Python file you wrote or changed imports and parses.
- The API client exists with centralized request handling, error mapping, and one \
domain method per action; actions call those methods and never build URLs or \
import an HTTP library themselves.
- The connection's connect() and test() are really implemented -- no `pass`, no \
`TODO`.
- Unit tests exist for each action against a mocked client, and they pass -- no \
`self.fail("Unimplemented Test Case")` stubs left behind.
- requirements.txt exists, with any dependency pinned exactly.

Do not stop at the first plausible draft. Run the checks, read the failures, fix \
them, and re-run.

When you are done, report in a few lines: what you implemented, what commands you \
ran to verify it, and anything still outstanding. If you could not reach the bar \
above, say so explicitly and name what is failing -- never report success with \
known failures open.
"""


class AgentConfigError(Exception):
    """Raised when the agent config cannot be written."""


@dataclass(frozen=True)
class AgentConfig:
    """A Kiro CLI agent configuration.

    Attributes:
        name: the agent name, selected via ``kiro-cli chat --agent <name>``.
        description: human-readable description; carries
            :data:`GENERATED_MARKER` for configs this tool owns.
        prompt: the standing system prompt (task framing + definition of done).
        tools: the tools the agent may use.
        resources: skill/steering files loaded into the agent's context. Entries
            are plain paths here; :meth:`to_dict` renders them as ``file://`` URIs.
        model: an explicit model id, or ``None`` to use the CLI's configured
            default. Left unset by default so the operator's own model choice
            wins rather than being pinned here.
    """

    name: str = AGENT_NAME
    description: str = f"Implements InsightConnect plugins from plugin.spec.yaml. {GENERATED_MARKER}"
    prompt: str = _SYSTEM_PROMPT
    tools: Tuple[str, ...] = DEFAULT_TOOLS
    resources: Tuple[str, ...] = field(default_factory=default_skill_resources)
    model: Optional[str] = None

    def to_dict(self) -> Dict[str, object]:
        """Render the config as the JSON structure the Kiro CLI expects.

        ``allowedTools`` mirrors ``tools``: the CLI runs non-interactively here,
        so a tool that is available but untrusted would stall waiting for a
        confirmation nobody can give. Narrowing happens by *not listing* a tool
        in :attr:`tools` at all.
        """
        return {
            "name": self.name,
            "description": self.description,
            "prompt": self.prompt,
            "mcpServers": {},
            "tools": list(self.tools),
            "toolAliases": {},
            "allowedTools": list(self.tools),
            "resources": [f"file://{resource}" for resource in self.resources],
            "toolsSettings": {},
            # The operator's MCP servers are irrelevant to building a plugin and
            # would widen the agent's reach; keep them out.
            "includeMcpJson": False,
            "model": self.model,
        }

    def to_json(self) -> str:
        """Render the config as formatted JSON with a trailing newline."""
        return json.dumps(self.to_dict(), indent=2, sort_keys=False) + "\n"


def default_agent_config(*, resources: Optional[Sequence[str]] = None) -> AgentConfig:
    """Build the default agent config, optionally overriding its resources.

    Args:
        resources: replacement skill/steering paths. ``None`` keeps
            the resolved rulebook.

    Returns:
        The :class:`AgentConfig` this tool delegates plugin implementation to.
    """
    if resources is None:
        return AgentConfig()
    return AgentConfig(resources=tuple(str(resource) for resource in resources))


def agent_config_path(*, kiro_home: Optional[Path] = None, name: str = AGENT_NAME) -> Path:
    """Return the path a named agent's config lives at.

    Args:
        kiro_home: the Kiro home directory; resolved via :func:`resolve_kiro_home`
            when omitted.
        name: the agent name.

    Returns:
        ``<kiro_home>/agents/<name>.json``.
    """
    base = resolve_kiro_home() if kiro_home is None else Path(kiro_home)
    return base / "agents" / f"{name}.json"


def write_agent_config(
    config: Optional[AgentConfig] = None,
    *,
    kiro_home: Optional[Path] = None,
    prune_missing_resources: bool = True,
) -> Path:
    """Write the agent config so ``kiro-cli --agent <name>`` can find it.

    Idempotent, and deliberately conservative about a pre-existing file: a config
    this tool generated (identified by :data:`GENERATED_MARKER` in its
    description) is overwritten so fixes and new skill references take effect,
    but a file the operator wrote themselves is left untouched and reported, so
    this tool never silently discards hand-authored agent configuration.

    Args:
        config: the config to write; the default is used when omitted.
        kiro_home: the Kiro home directory; resolved from the environment when
            omitted.
        prune_missing_resources: when ``True`` (the default), resource paths that
            do not exist on disk are dropped before writing. The Kiro CLI treats
            an unresolvable resource as an error, and an operator who has not
            installed the workflow skills should still get a usable agent.

    Returns:
        The path written, or the path of the pre-existing operator-owned config
        that was left in place.

    Raises:
        AgentConfigError: if the directory cannot be created or the file cannot
            be written.
    """
    resolved = config if config is not None else default_agent_config()

    if prune_missing_resources:
        present = tuple(resource for resource in resolved.resources if Path(resource).expanduser().is_file())
        if present != resolved.resources:
            resolved = AgentConfig(
                name=resolved.name,
                description=resolved.description,
                prompt=resolved.prompt,
                tools=resolved.tools,
                resources=present,
                model=resolved.model,
            )

    path = agent_config_path(kiro_home=kiro_home, name=resolved.name)

    if path.exists() and not _is_generated(path):
        # Operator-authored config at our name: respect it, do not clobber.
        return path

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(resolved.to_json(), encoding="utf-8")
    except OSError as error:
        raise AgentConfigError(f"failed to write the agent config to {path}: {error}") from error

    return path


def missing_resources(config: Optional[AgentConfig] = None) -> Tuple[str, ...]:
    """Return the config's resource paths that are not present on disk.

    Lets a caller warn that the agent will run with reduced guidance because some
    of the operator's plugin skills are not installed, rather than discovering it
    from lower-quality output later.

    Args:
        config: the config to check; the default is used when omitted.

    Returns:
        The absent resource paths, in the order they are declared.
    """
    resolved = config if config is not None else default_agent_config()
    return tuple(resource for resource in resolved.resources if not Path(resource).expanduser().is_file())


def _is_generated(path: Path) -> bool:
    """Return ``True`` iff the config at ``path`` was generated by this tool.

    A file that cannot be read or parsed is treated as *not* generated, so the
    conservative branch (leave it alone) is taken on any doubt.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    if not isinstance(data, dict):
        return False
    return GENERATED_MARKER in str(data.get("description", ""))
