"""The LLM_Generator: scoped Kiro CLI dispatch with cost gating (task 14.1).

The ``LLM_Generator`` is the *reasoning* half of the generation split (design
"Generation_Engine -> LLM_Generator"). Everything mechanical is produced by the
``insight-plugin`` CLI and template rendering with zero LLM calls; this wrapper
is invoked **only** for the three reasoning artifact kinds -- action logic,
field descriptions, and help text (Req 3.2) -- and only when no matching
template is available (Req 3.4). Each artifact is generated by prompting the
Kiro CLI as a subprocess through :func:`asyncio.create_subprocess_exec`, feeding
it only the relevant scoped slice of the spec (design "Prompt scoping").

Every dispatch is gated by the :class:`~icplugin_builder.core.cost_controller.CostController`:

* :meth:`LLMGenerator.generate` first calls :meth:`CostController.authorize`;
  when the session token budget is reached or the per-user request rate is
  exceeded, the invocation is **not** dispatched and a :class:`CostLimitError`
  carrying the controller's :class:`Decision` is raised (Req 4.2, 4.5).
* On a successful invocation the tokens consumed are recorded on the session's
  cumulative total via :meth:`CostController.record_usage` (Req 3.5).
* If the invocation fails -- the Kiro CLI cannot be launched or exits non-zero
  -- the step is halted and the invocation is excluded from the cumulative total
  by recording it as a failure (Req 3.7).

**Token measurement precedence** (design "Token accounting with the Kiro CLI"):
1. If the Kiro CLI emits a machine-readable usage figure (structured JSON on
   stdout or a ``total_tokens: N`` usage line), that reported value is used.
2. Otherwise tokens are **estimated** from the prompt plus completion text with a
   ~4-characters-per-token heuristic and flagged as an estimate so the UI can
   mark the session total accordingly.
The recorded figure is always a non-negative integer (Req 3.6).
"""

from __future__ import annotations

import asyncio
import json
import math
import re
from dataclasses import dataclass
from typing import Any, Mapping, Optional, Sequence, Union

from icplugin_builder.core.cost_controller import CostController, Decision
from icplugin_builder.core.generation import REASONING_ARTIFACT_KINDS, ArtifactKind

__all__ = [
    "DEFAULT_EXECUTABLE",
    "CHARS_PER_TOKEN",
    "TOKEN_SOURCE_REPORTED",
    "TOKEN_SOURCE_ESTIMATED",
    "LLMGeneratorError",
    "CostLimitError",
    "TokenMeasurement",
    "GenerationResult",
    "LLMGenerator",
    "estimate_tokens",
    "parse_reported_tokens",
]

#: The default Kiro CLI executable name (resolved on ``PATH``).
DEFAULT_EXECUTABLE = "kiro"

#: The character-per-token divisor for the estimation fallback (~4 chars/token).
CHARS_PER_TOKEN = 4

#: Token-measurement source markers recorded alongside the figure.
TOKEN_SOURCE_REPORTED = "reported"
TOKEN_SOURCE_ESTIMATED = "estimated"

#: JSON/usage-line keys that carry a machine-readable token figure, in priority order.
_USAGE_KEYS = ("total_tokens", "token_count", "tokens")

#: Matches a ``key: N`` / ``key=N`` usage line emitted by the CLI.
_USAGE_LINE = re.compile(
    r"\b(?:total_tokens|token_count|tokens)\b\s*[:=]\s*(\d+)",
    re.IGNORECASE,
)


class LLMGeneratorError(Exception):
    """Raised when a Kiro CLI invocation cannot be dispatched or fails.

    Carries the argument vector, exit code, and captured output so the caller can
    surface the failing step and its error message (Req 3.7, 19.1).
    """

    def __init__(
        self,
        message: str,
        *,
        command: Optional[Sequence[str]] = None,
        returncode: Optional[int] = None,
        stdout: str = "",
        stderr: str = "",
    ) -> None:
        super().__init__(message)
        self.command = tuple(command) if command is not None else ()
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


class CostLimitError(LLMGeneratorError):
    """Raised when the Cost_Controller blocks an invocation before dispatch.

    The invocation never reached the Kiro CLI: the session token budget was
    reached (Req 4.2) or the per-user request rate was exceeded (Req 4.5). The
    controller's :class:`Decision` -- including its user-facing ``message`` and,
    for a rate-limit rejection, ``retry_after_seconds`` -- is attached so the
    caller can surface it verbatim.
    """

    def __init__(self, decision: Decision) -> None:
        super().__init__(decision.message or "LLM invocation blocked by cost controls")
        self.decision = decision


@dataclass(frozen=True)
class TokenMeasurement:
    """How many tokens an invocation consumed and how that figure was obtained.

    Attributes:
        tokens: the non-negative token count (Req 3.6).
        source: :data:`TOKEN_SOURCE_REPORTED` when taken from the Kiro CLI's own
            machine-readable usage figure, or :data:`TOKEN_SOURCE_ESTIMATED` when
            derived from the ~4-chars/token heuristic fallback.
    """

    tokens: int
    source: str

    @property
    def estimated(self) -> bool:
        """Return ``True`` iff the figure is an estimate rather than reported."""
        return self.source == TOKEN_SOURCE_ESTIMATED


@dataclass(frozen=True)
class GenerationResult:
    """The outcome of a successful :meth:`LLMGenerator.generate` call.

    Attributes:
        kind: the reasoning :class:`ArtifactKind` that was generated.
        content: the artifact text returned by the Kiro CLI.
        measurement: the token figure and its source for this invocation.
        session_total: the cumulative session token total after recording this
            invocation (Req 3.5, 3.6).
    """

    kind: ArtifactKind
    content: str
    measurement: TokenMeasurement
    session_total: int

    @property
    def tokens(self) -> int:
        """The tokens consumed by this invocation."""
        return self.measurement.tokens

    @property
    def estimated(self) -> bool:
        """Return ``True`` iff the token figure is an estimate (Req token accounting)."""
        return self.measurement.estimated


# --- Kiro CLI output cleaning ------------------------------------------------

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _clean_cli_output(stdout: str) -> str:
    """Strip ANSI codes, the Kiro CLI '> ' prefix, markdown fences, and the credits footer.

    Returns the LLM-generated content only, suitable for use as an artifact body.
    """
    text = _ANSI_RE.sub("", stdout)
    lines = text.strip().split("\n")
    # Remove trailing credits/timing line (e.g. " ▸ Credits: 0.05 • Time: 2s")
    while lines and (lines[-1].strip().startswith("\u25b8") or lines[-1].strip() == ""):
        lines.pop()
    # Strip leading "> " prompt prefix from each line
    cleaned = []
    for line in lines:
        if line.startswith("> "):
            cleaned.append(line[2:])
        else:
            cleaned.append(line)
    # Remove markdown fence artifacts that leak from the LLM (```python, ```, bare "python")
    final = []
    for line in cleaned:
        stripped = line.strip()
        if stripped in ("```python", "```", "python"):
            continue
        final.append(line)
    return "\n".join(final).strip()


def _build_action_logic_prompt(context: Mapping[str, Any]) -> str:
    """Build a detailed prompt for generating InsightConnect action Python code."""
    action_name = context.get("action", "unknown")
    action_title = context.get("action_title", action_name)
    action_desc = context.get("action_description", "")
    plugin_name = context.get("plugin_name", "")
    plugin_desc = context.get("plugin_description", "")
    connection_fields = context.get("connection_fields", {})
    input_fields = context.get("input_fields", {})
    output_fields = context.get("output_fields", {})

    # API endpoint details (may be populated from OpenAPI spec if available)
    api_method = context.get("api_method", "")
    api_path = context.get("api_path", "")
    api_query_params = context.get("api_query_params", [])
    api_request_body = context.get("api_request_body", "")
    api_response_shape = context.get("api_response_shape", "")
    api_success_status = context.get("api_success_status", 200)

    connection_summary = ""
    if connection_fields:
        lines = []
        for name, info in connection_fields.items():
            lines.append(f"  - {name} ({info.get('type', 'string')}): {info.get('description', '')}")
        connection_summary = "\n".join(lines)

    input_summary = ""
    if input_fields:
        lines = []
        for name, info in input_fields.items():
            req = "required" if info.get("required") else "optional"
            lines.append(f"  - {name} ({info.get('type', 'string')}, {req}): {info.get('description', '')}")
        input_summary = "\n".join(lines)

    output_summary = ""
    if output_fields:
        lines = []
        for name, info in output_fields.items():
            req = "required" if info.get("required") else "optional"
            lines.append(f"  - {name} ({info.get('type', 'string')}, {req}): {info.get('description', '')}")
        output_summary = "\n".join(lines)

    api_section = ""
    if api_path:
        api_section = "\n## API Endpoint\n\n"
        api_section += f"HTTP method: {api_method}\n"
        api_section += f"Full path: https://{{region}}.api.insight.rapid7.com/{api_path.lstrip('/')}\n"
        api_section += f"Expected success status: {api_success_status}\n"
        if api_query_params:
            api_section += f"Query parameters: {', '.join(api_query_params)}\n"
        if api_request_body:
            api_section += f"Request body schema:\n{api_request_body}\n"
        if api_response_shape:
            api_section += f"Response shape:\n{api_response_shape}\n"
        if api_success_status == 204:
            api_section += (
                "IMPORTANT: 204 means success with NO response body. "
                "Do NOT call response.json(). Just check status_code.\n"
            )

    prompt_parts = []
    prompt_parts.append(
        "You are writing Python code for a Rapid7 InsightConnect plugin action.\n"
        "Respond with ONLY the Python code body for the run() method. No explanation,\n"
        "no markdown fences, no class definition, no language identifiers — just raw\n"
        "Python code that goes AFTER the input bindings and BEFORE the end of the method."
    )
    prompt_parts.append(f"\n## Context\n\nPlugin: {plugin_name} — {plugin_desc}")
    prompt_parts.append(f"Action: {action_name} ({action_title}) — {action_desc}")
    prompt_parts.append(f"\nConnection fields (available via self.connection):\n{connection_summary or '  (none)'}")
    if api_section:
        prompt_parts.append(api_section)
    prompt_parts.append(
        f"\nInput parameters (already bound to local variables via params.get(Input.X)):\n"
        f"{input_summary or '  (none)'}"
    )
    prompt_parts.append(
        f"\nExpected output (return a dict matching these Output constant keys):\n" f"{output_summary or '  (none)'}"
    )
    prompt_parts.append("""
## Mandatory patterns

1. Use `requests` for HTTP calls (already imported in the file).
2. Access connection: self.connection.region, self.connection.org_id, self.connection.api_key.
3. For credential_token fields (api_key): it is ALREADY a plain string.
   Access directly as self.connection.api_key. Do NOT call .get("secretKey") or .get("token").
4. Base URL: f"https://{self.connection.region}.api.insight.rapid7.com"
5. Service path prefix for this plugin: /insight-velociraptor/v1/orgs/{self.connection.org_id}/
6. Headers: {"X-Api-Key": self.connection.api_key, "Content-Type": "application/json"}
7. Error handling: raise PluginException(cause=..., assistance=..., data=response.text)
   (PluginException is already imported in the file).
8. For paginated responses, the JSON uses: {"data": [...], "cursor": "...", "size": N}.
   Parse with .get("data", []) and .get("cursor", "").
9. Wrap the return dict in clean() (already imported) when any output is optional.
   This strips None/empty values.
10. NEVER shadow Python builtins as variable names: avoid os, type, id, list, filter,
    format, hash, map, range, set. Use os_filter, artifact_type, client_id, etc.
11. Status code handling: check response.status_code against the expected success code.
    For 204, do NOT parse JSON — just return the success indicator dict.
12. All actions in this plugin MUST use the same URL prefix pattern consistently.
13. Do NOT output any markdown, code fences, or the word 'python' on its own line.
14. Do NOT include imports, class definition, method signature, or input bindings.

## Output

Raw Python code only. Nothing else.""")

    return "\n".join(prompt_parts) + "\n"


def estimate_tokens(text: str) -> int:
    """Estimate the token count of ``text`` with a ~4-characters-per-token heuristic.

    This is the fallback used when the Kiro CLI does not report an exact figure
    (design "Token accounting with the Kiro CLI", step 2). The result is a
    non-negative integer; empty text estimates to ``0``.
    """
    if not text:
        return 0
    return math.ceil(len(text) / CHARS_PER_TOKEN)


def parse_reported_tokens(stdout: str) -> Optional[int]:
    """Extract a machine-readable token figure from Kiro CLI ``stdout``.

    Recognizes, in order: the whole output parsed as a JSON object carrying a
    usage figure (``total_tokens`` / ``token_count`` / ``tokens``, possibly nested
    under a ``usage`` object), a single line that is such a JSON object, or a
    plain ``total_tokens: N`` / ``tokens=N`` usage line.

    Returns:
        The reported non-negative token count, or ``None`` when no reliable
        figure is present (in which case the caller estimates instead).
    """
    if not stdout:
        return None

    whole = _tokens_from_json(stdout.strip())
    if whole is not None:
        return whole

    for line in stdout.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        from_json = _tokens_from_json(stripped)
        if from_json is not None:
            return from_json
        match = _USAGE_LINE.search(stripped)
        if match is not None:
            return int(match.group(1))
    return None


def _tokens_from_json(text: str) -> Optional[int]:
    """Return a usage figure from ``text`` parsed as JSON, or ``None``."""
    try:
        data = json.loads(text)
    except (ValueError, TypeError):
        return None
    return _search_usage(data)


def _search_usage(data: Any) -> Optional[int]:
    """Search a decoded JSON value for a usage figure under a known key."""
    if not isinstance(data, Mapping):
        return None
    for key in _USAGE_KEYS:
        if key in data:
            value = _coerce_non_negative_int(data[key])
            if value is not None:
                return value
    for value in data.values():
        found = _search_usage(value)
        if found is not None:
            return found
    return None


def _coerce_non_negative_int(value: Any) -> Optional[int]:
    """Coerce ``value`` to a non-negative int, or ``None`` if it is not one."""
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value if value >= 0 else None
    if isinstance(value, str):
        try:
            parsed = int(value.strip())
        except ValueError:
            return None
        return parsed if parsed >= 0 else None
    return None


class LLMGenerator:
    """Async wrapper over the Kiro CLI that generates reasoning artifacts.

    The wrapper is deliberately thin: it validates that the requested kind is a
    reasoning kind, gates the call through the :class:`CostController`, builds a
    scoped prompt, runs the Kiro CLI via :func:`asyncio.create_subprocess_exec`,
    measures the tokens consumed, and records the usage on the session total. It
    is the *only* seam that invokes the LLM (Req 3.2).
    """

    def __init__(
        self,
        cost_controller: CostController,
        executable: Union[str, Sequence[str]] = DEFAULT_EXECUTABLE,
    ) -> None:
        """Configure the generator.

        Args:
            cost_controller: the shared :class:`CostController` every invocation
                is authorized and recorded against.
            executable: the Kiro CLI command -- either the binary name/path or a
                full argument-vector prefix (e.g. ``["kiro", "generate"]``).
        """
        self._cost_controller = cost_controller
        if isinstance(executable, str):
            self._command_prefix = [executable]
        else:
            self._command_prefix = [str(part) for part in executable]

    @property
    def cost_controller(self) -> CostController:
        """The :class:`CostController` this generator gates through."""
        return self._cost_controller

    async def generate(
        self,
        kind: Union[ArtifactKind, str],
        scoped_context: Mapping[str, Any],
        *,
        session_id: str,
        user_id: str,
    ) -> GenerationResult:
        """Generate a reasoning artifact through the Kiro CLI, gated by cost.

        Args:
            kind: the artifact kind; must be one of the reasoning kinds
                (``action_logic``, ``field_description``, ``help_text``) -- the
                only kinds the LLM is ever invoked for (Req 3.2). Deterministic
                kinds are rejected before any dispatch.
            scoped_context: the relevant slice of the spec to prompt with (the
                single action being authored plus the connection contract, etc.);
                the whole project tree is never sent (design "Prompt scoping").
            session_id: the session whose token budget and cumulative total
                govern and record this invocation.
            user_id: the user whose per-minute request rate governs this
                invocation.

        Returns:
            A :class:`GenerationResult` with the generated content, the token
            measurement, and the updated cumulative session total.

        Raises:
            ValueError: if ``kind`` is not a reasoning artifact kind.
            CostLimitError: if the Cost_Controller blocks the invocation (budget
                reached or rate limit exceeded); nothing is dispatched.
            LLMGeneratorError: if the Kiro CLI cannot be launched or exits
                non-zero; the invocation is excluded from the session total.
        """
        resolved_kind = self._resolve_reasoning_kind(kind)

        decision = self._cost_controller.authorize(session_id, user_id)
        if not decision.authorized:
            raise CostLimitError(decision)

        prompt = self._build_prompt(resolved_kind, scoped_context)
        command = [*self._command_prefix, "chat", "--no-interactive"]

        try:
            returncode, stdout, stderr = await self._invoke(command, prompt)
        except FileNotFoundError as error:
            # The invocation never produced output; exclude it from the total (Req 3.7).
            self._cost_controller.record_usage(session_id, estimate_tokens(prompt), succeeded=False)
            raise LLMGeneratorError(
                f"Kiro CLI executable not found: {self._command_prefix[0]!r}; "
                "install the Kiro CLI and ensure it is on PATH",
                command=command,
            ) from error

        if returncode != 0:
            # Failed invocation: halt the step, exclude from the total (Req 3.7).
            self._cost_controller.record_usage(session_id, estimate_tokens(prompt), succeeded=False)
            raise LLMGeneratorError(
                f"Kiro CLI generation for {resolved_kind.value!r} failed with exit code {returncode}",
                command=command,
                returncode=returncode,
                stdout=stdout,
                stderr=stderr,
            )

        content = _clean_cli_output(stdout)
        measurement = self._measure_tokens(prompt=prompt, stdout=stdout, content=content)
        session_total = self._cost_controller.record_usage(session_id, measurement.tokens, succeeded=True)
        return GenerationResult(
            kind=resolved_kind,
            content=content,
            measurement=measurement,
            session_total=session_total,
        )

    @staticmethod
    def _resolve_reasoning_kind(kind: Union[ArtifactKind, str]) -> ArtifactKind:
        """Coerce ``kind`` to an :class:`ArtifactKind` and require a reasoning kind.

        Raises:
            ValueError: if ``kind`` is unknown or not a reasoning kind. The LLM is
                never invoked for deterministic artifacts (Req 3.2).
        """
        try:
            resolved = ArtifactKind(kind)
        except ValueError as error:
            raise ValueError(f"unknown artifact kind: {kind!r}") from error
        if resolved not in REASONING_ARTIFACT_KINDS:
            raise ValueError(
                f"{resolved.value!r} is not a reasoning artifact kind; the LLM_Generator only serves "
                f"{', '.join(sorted(k.value for k in REASONING_ARTIFACT_KINDS))}"
            )
        return resolved

    @staticmethod
    def _build_prompt(kind: ArtifactKind, scoped_context: Mapping[str, Any]) -> str:
        """Build the scoped Kiro CLI prompt for ``kind`` from ``scoped_context``.

        Produces a structured prompt that tells the LLM exactly what code to
        generate, including the action's I/O schema and connection details.
        """
        if kind == ArtifactKind.ACTION_LOGIC:
            return _build_action_logic_prompt(scoped_context)
        # Fallback for other reasoning kinds (field_description, help_text).
        try:
            context_json = json.dumps(dict(scoped_context), sort_keys=True, default=str)
        except (TypeError, ValueError):
            context_json = json.dumps({key: str(value) for key, value in dict(scoped_context).items()}, sort_keys=True)
        return f"kind={kind.value}\ncontext={context_json}\n"

    def _measure_tokens(self, *, prompt: str, stdout: str, content: str) -> TokenMeasurement:
        """Measure tokens by the reported figure, falling back to an estimate.

        Prefers a machine-readable usage figure from the Kiro CLI ``stdout``
        (step 1); otherwise estimates from the prompt plus the completion content
        (step 2), flagged as an estimate.
        """
        reported = parse_reported_tokens(stdout)
        if reported is not None:
            return TokenMeasurement(tokens=reported, source=TOKEN_SOURCE_REPORTED)
        estimated = estimate_tokens(prompt) + estimate_tokens(content)
        return TokenMeasurement(tokens=estimated, source=TOKEN_SOURCE_ESTIMATED)

    async def _invoke(self, command: Sequence[str], prompt: str) -> tuple:
        """Run the Kiro CLI ``command``, feeding ``prompt`` on stdin.

        Returns:
            A ``(returncode, stdout, stderr)`` tuple with the decoded output.

        Raises:
            FileNotFoundError: if the executable cannot be found.
        """
        process = await asyncio.create_subprocess_exec(
            *command,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout_bytes, stderr_bytes = await process.communicate(prompt.encode("utf-8"))
        stdout = stdout_bytes.decode("utf-8", errors="replace")
        stderr = stderr_bytes.decode("utf-8", errors="replace")
        returncode = process.returncode if process.returncode is not None else -1
        return returncode, stdout, stderr
