"""Runs the toolchain's own validators, minus the ones a standalone plugin cannot satisfy.

`insight-plugin validate` is the bar a plugin has to clear. It is also, invoked
plainly, unusable here -- and not because a check fails. Its
``Version Increment Validator`` fetches the plugin's previous spec from the
``insightconnect-plugins`` git remote, deriving the path by splitting on
``/plugins/``. A plugin generated by this tool lives in neither a clone nor such a
path, so the validator raises ``InvalidGitRepositoryError``, then a ``TypeError``
while handling it, and the process dies with a traceback.

The consequence is worse than one spurious failure, and it is the reason this
module exists. Measured on a real generated plugin:

* 33 of 41 validators ran; the crash aborted the rest, so ``NameValidator`` and
  every security-oriented validator -- credentials, passwords, confidential data,
  print statements, exception handling -- never executed at all;
* ``validate()`` prints its collected failures *after* the loop, so the crash
  suppressed the report entirely: eleven genuine failures on that plugin were
  reported as nothing but a stack trace.

Excluding that single validator turns a crash into a usable report: 40 validators
run and the eleven real failures are named.

**Exclusions are named, justified, and few.** Every validator in
:data:`EXCLUDED_VALIDATORS` carries the reason it cannot apply, and the list was
built by inspection rather than by suppressing whatever complained: exactly one
validator in the installed set has a hard dependency on the plugins repository.
An exclusion is a statement that a check *cannot* be satisfied outside the
repository, never that it is inconvenient.

The verdict itself still comes from the toolchain: this module hands
``icon_validator`` a validator list and reports the status it returns. It does not
reimplement a single check.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, Mapping, Optional, Tuple, Union

__all__ = [
    "EXCLUDED_VALIDATORS",
    "VALIDATE_DRIVER",
    "excluded_validator_names",
    "validate_command",
]

#: Validators that cannot apply to a plugin developed outside the
#: ``insightconnect-plugins`` repository, each with the reason. Keyed by the
#: validator's own ``name`` attribute, which is what ``icon_validator`` reports and
#: what the driver filters on.
EXCLUDED_VALIDATORS: Mapping[str, str] = {
    "Version Increment Validator": (
        "compares the spec against the previous version fetched from the "
        "insightconnect-plugins git remote, and locates the plugin by splitting its "
        "path on '/plugins/'. A plugin generated here is in neither a clone of that "
        "repository nor such a path, so this raises InvalidGitRepositoryError rather "
        "than reporting a validation failure -- and because the exception is "
        "unhandled it aborts the entire run, skipping every validator after it and "
        "suppressing the failures already collected. Version arithmetic is done by "
        "this tool's own version_bump module instead."
    ),
}

#: Driver executed by the interpreter that has ``icon_validator`` installed -- the
#: toolchain's interpreter, not this tool's. A generated plugin's spec is parsed by
#: ``icon_validator`` itself, so the package must be importable where this runs.
#:
#: The validator list is rebuilt from scratch rather than reusing the module-level
#: ``VALIDATORS``: ``icon_validator.validate`` does ``validators += JENKINS_VALIDATORS``
#: on that very list, mutating it in place, so its contents depend on whether
#: anything has called ``validate`` earlier in the process.
VALIDATE_DRIVER = """
import json
import sys

try:
    from icon_validator.rules import JENKINS_VALIDATORS, VALIDATORS
    from icon_validator.validate import validate
except ImportError as error:
    sys.stderr.write(
        "icon_validator is not importable by this interpreter (%s); "
        "insight-plugin and its validators must be installed where the plugin "
        "toolchain runs.\\n" % error
    )
    raise SystemExit(3)

directory = sys.argv[1]
excluded = set(json.loads(sys.argv[2]))

everything = list(VALIDATORS) + list(JENKINS_VALIDATORS)
kept = [v for v in everything if v.name not in excluded]
missing = sorted(excluded - {v.name for v in everything})

status = validate(directory, validators=kept)

# Printed last so it survives truncation of the report above, and so a reader
# sees the count that ran alongside the count that was deliberately left out.
skipped = ", ".join(sorted(excluded - set(missing))) or "none"
if missing:
    print("note: excluded validators not present in this toolchain: %s" % ", ".join(missing))
print(
    "validators: %d ran of %d available; excluded: %s"
    % (len(kept), len(everything), skipped)
)
raise SystemExit(status)
"""


def excluded_validator_names(excluded: Optional[Iterable[str]] = None) -> Tuple[str, ...]:
    """Return the validator names to exclude, sorted.

    Args:
        excluded: an explicit set of names, for a caller that needs to widen or
            narrow the default. ``None`` uses :data:`EXCLUDED_VALIDATORS`.

    Returns:
        The names, sorted so a command built from them is deterministic.
    """
    names = EXCLUDED_VALIDATORS.keys() if excluded is None else excluded
    return tuple(sorted(names))


def validate_command(
    project_dir: Union[str, Path],
    *,
    python_executable: str = "python3",
    excluded: Optional[Iterable[str]] = None,
) -> Tuple[str, ...]:
    """Build the command that validates ``project_dir`` with the excluded checks skipped.

    Args:
        project_dir: the plugin working tree to validate.
        python_executable: the interpreter that has ``icon_validator`` installed.
            Resolve it with
            :func:`~icplugin_builder.integrations.build_prep.resolve_target_python`;
            this tool's own interpreter does not have the plugin toolchain.
        excluded: validator names to skip. ``None`` uses
            :data:`EXCLUDED_VALIDATORS`.

    Returns:
        The argument vector. Exit status is ``icon_validator``'s own: ``0`` when
        every validator that ran passed, ``1`` when any failed, and ``3`` when the
        validators are not installed for that interpreter.
    """
    return (
        python_executable,
        "-c",
        VALIDATE_DRIVER,
        str(project_dir),
        json.dumps(list(excluded_validator_names(excluded))),
    )
