"""Structural-change detection that gates the post-edit ``insight-plugin refresh``.

Req 22.3 (design "refresh after spec edit"; design Property 40) requires that
whenever an iteration on a loaded plugin **adds or changes** an action, trigger,
task, or connection, the derived scaffolding (``schema.py``, ``__init__.py``,
``Dockerfile``, ``Makefile``, ``setup.py``, ``help.md``, ``.CHECKSUM``) is
regenerated by the deterministic ``insight-plugin refresh`` operation rather
than hand-edited.

This module supplies the two pieces that enforce that guarantee:

* :func:`detect_structural_change` compares the *old* (previously exported /
  loaded) :class:`~icplugin_builder.core.spec_model.PluginSpec` against the
  *new* (current draft) spec and reports whether any of the four structural
  sections -- ``connection``, ``actions``, ``triggers``, ``tasks`` -- was added
  to, removed from, or modified. Metadata-only edits that leave all four
  sections structurally identical are *not* structural and need no refresh.
* :class:`RefreshCoordinator` ties detection to the CLI: it invokes
  :meth:`InsightPluginCli.refresh` exactly when a structural change is present,
  so the on-disk derived files always equal the refresh output.

Neither path performs any LLM call: detection is a pure comparison of the typed
spec tree and the refresh is delegated to the deterministic CLI wrapper.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Mapping, Optional, Tuple

from icplugin_builder.core.spec_model import PluginSpec
from icplugin_builder.integrations.insight_plugin_cli import InsightPluginCli, PathInput, ProjectTree

__all__ = [
    "STRUCTURAL_SECTIONS",
    "StructuralChange",
    "detect_structural_change",
    "RefreshCoordinator",
]

#: The spec sections whose addition/removal/modification requires a
#: deterministic ``insight-plugin refresh`` (Req 22.3).
STRUCTURAL_SECTIONS: Tuple[str, ...] = ("connection", "actions", "triggers", "tasks")


@dataclass(frozen=True)
class StructuralChange:
    """The outcome of comparing two specs' structural surfaces.

    Attributes:
        changed_sections: The structural sections (a subset of
            :data:`STRUCTURAL_SECTIONS`, in that stable order) that differ
            between the two specs. Empty iff the change is non-structural.
        reasons: One human-readable message per detected structural difference,
            in a stable order, suitable for surfacing why a refresh was run.
    """

    changed_sections: Tuple[str, ...] = ()
    reasons: Tuple[str, ...] = ()

    @property
    def is_structural(self) -> bool:
        """Return ``True`` iff at least one structural section changed."""
        return bool(self.changed_sections)

    def __bool__(self) -> bool:  # pragma: no cover - convenience only
        return self.is_structural


def detect_structural_change(old: Optional[PluginSpec], new: PluginSpec) -> StructuralChange:
    """Detect whether ``new`` adds or changes an action/trigger/task/connection.

    Compares the four structural sections of ``old`` and ``new``. A section is
    considered changed when a named component is added, removed, or has a
    differing structural definition (``Component``/``FieldSchema`` equality). A
    ``None`` ``old`` is treated as an empty baseline, so every populated
    structural section in ``new`` is reported as an addition.

    Args:
        old: The previously exported/loaded spec, or ``None`` when there is no
            prior baseline.
        new: The current draft spec.

    Returns:
        A :class:`StructuralChange`; ``is_structural`` is ``True`` iff any of the
        ``connection``, ``actions``, ``triggers``, or ``tasks`` sections differ.
    """
    baseline = old if old is not None else PluginSpec()

    changed_sections: List[str] = []
    reasons: List[str] = []

    connection_reasons = _diff_named_map(baseline.connection, new.connection, label="connection field")
    if connection_reasons:
        changed_sections.append("connection")
        reasons.extend(connection_reasons)

    for section, old_components, new_components in (
        ("actions", baseline.actions, new.actions),
        ("triggers", baseline.triggers, new.triggers),
        ("tasks", baseline.tasks, new.tasks),
    ):
        section_reasons = _diff_named_map(old_components, new_components, label=_singular(section))
        if section_reasons:
            changed_sections.append(section)
            reasons.extend(section_reasons)

    return StructuralChange(changed_sections=tuple(changed_sections), reasons=tuple(reasons))


class RefreshCoordinator:
    """Runs ``insight-plugin refresh`` exactly when a structural change occurs.

    The coordinator is the enforcement point for Req 22.3: it never hand-edits
    derived files. When an iteration changes the spec's structural surface it
    delegates to :meth:`InsightPluginCli.refresh` so the derived files on disk
    equal the refresh output; when the change is non-structural it does nothing.
    """

    def __init__(self, cli: Optional[InsightPluginCli] = None) -> None:
        """Configure the coordinator.

        Args:
            cli: The CLI wrapper used to run ``insight-plugin refresh``. A
                default :class:`InsightPluginCli` is created when omitted.
        """
        self._cli = cli if cli is not None else InsightPluginCli()

    @property
    def cli(self) -> InsightPluginCli:
        """The underlying ``insight-plugin`` CLI wrapper."""
        return self._cli

    async def refresh_if_structural(
        self,
        old: Optional[PluginSpec],
        new: PluginSpec,
        project_dir: PathInput,
    ) -> Optional[ProjectTree]:
        """Refresh derived files iff ``new`` structurally changed ``old``.

        Args:
            old: The previously exported/loaded spec, or ``None`` for no prior
                baseline.
            new: The current draft spec.
            project_dir: The plugin working tree to refresh.

        Returns:
            The :class:`ProjectTree` produced by ``insight-plugin refresh`` when
            a structural change was detected, or ``None`` when no refresh was
            needed (the change was non-structural).

        Raises:
            InsightPluginCliError: if the refresh invocation fails.
        """
        change = detect_structural_change(old, new)
        if not change.is_structural:
            return None
        return await self._cli.refresh(project_dir)


def _diff_named_map(
    old_map: Mapping[str, object],
    new_map: Mapping[str, object],
    *,
    label: str,
) -> List[str]:
    """Collect structural-change reasons between two name-keyed maps.

    Works uniformly for the connection field map (``name -> FieldSchema``) and
    the component maps (``name -> Component``); both compare by dataclass
    equality. Reports additions, removals, and modifications in a stable order
    (removed then added then modified, each sorted by name). ``label`` is the
    human noun for an entry, e.g. ``"action"`` or ``"connection field"``.
    """
    old_names = set(old_map)
    new_names = set(new_map)

    reasons: List[str] = []
    for name in sorted(old_names - new_names):
        reasons.append(f"{label} '{name}' was removed")
    for name in sorted(new_names - old_names):
        reasons.append(f"{label} '{name}' was added")
    for name in sorted(old_names & new_names):
        if old_map[name] != new_map[name]:
            reasons.append(f"{label} '{name}' was changed")
    return reasons


def _singular(section: str) -> str:
    """Return the singular noun for a component ``section`` name."""
    return {"actions": "action", "triggers": "trigger", "tasks": "task"}.get(section, section)
