"""Pure-logic core.

Spec model, semver/version-bump, breaking-change classification, ``_custom``
vendor suffixing, diffing, masking, token accounting, config validation, and
view-model/documentation generation. This layer has no I/O and no external
process dependencies so it can be exhaustively property-tested.
"""

from .atomic import (
    AtomicResult,
    AtomicState,
    atomic_apply,
    try_atomic_apply,
)
from .classifier import BreakingChangeResult, classify_change, is_breaking_change
from .cost_controller import (
    AUTHORIZED,
    BUDGET_REACHED,
    CostController,
    Decision,
    RATE_LIMITED,
    RATE_LIMIT_WINDOW_SECONDS,
)
from .diff import FileTreeDiff, diff_file_trees
from .documentation import (
    DocumentationError,
    MissingMetadataError,
    REQUIRED_METADATA_FIELDS,
    generate_help,
    write_help,
)
from .draft import (
    ComponentExistsError,
    ComponentKind,
    ComponentNotFoundError,
    Draft,
    DraftError,
)
from .generation import (
    ArtifactKind,
    Classification,
    DETERMINISTIC_ARTIFACT_KINDS,
    GenerationRequest,
    REASONING_ARTIFACT_KINDS,
    REQUESTABLE_ARTIFACT_KINDS,
    Route,
    Template,
    TemplateError,
    TemplateLibrary,
    classify_request,
    default_template_library,
)
from .input_validation import (
    InputRejectionReason,
    InputValidationResult,
    MAX_INPUT_LENGTH,
    MIN_INPUT_LENGTH,
    is_acceptable_length,
    is_blank,
    validate_conversation_input,
)
from .limits import (
    LimitOutOfRangeError,
    RATE_LIMIT_MAX,
    RATE_LIMIT_MIN,
    TOKEN_BUDGET_MAX,
    TOKEN_BUDGET_MIN,
    is_valid_rate_limit,
    is_valid_token_budget,
    validate_rate_limit,
    validate_token_budget,
)
from .masking import (
    MASK_PLACEHOLDER,
    mask_secret,
    redact_secret,
    redact_secrets,
)
from .spec_model import Component, FieldSchema, PluginSpec, SemVer
from .spec_validator import (
    PLUGIN_SPEC_SCHEMA,
    SpecValidationError,
    SpecValidator,
    ValidationReport,
    validate_spec,
)
from .truncation import MAX_DISPLAY_CHARS, TruncatedOutput, truncate_error_output
from .view_model import (
    ACTION,
    CONNECTION,
    FieldView,
    NodeNotFoundError,
    NodeView,
    TASK,
    TRIGGER,
    VisualizationViewModel,
    build_view_model,
)
from .visualization import (
    EMPTY_STATE_MESSAGE,
    VisualizationRender,
    VisualizationRenderer,
    VisualizationState,
    render_visualization,
)
from .token_accounting import (
    SessionTokenAccount,
    TokenInvocation,
    sum_successful_tokens,
)
from .vendor import CUSTOM_VENDOR_SUFFIX, apply_custom_vendor_suffix
from .version_bump import (
    BUMP_MAJOR,
    BUMP_NONE,
    BUMP_PATCH,
    VERSION_HISTORY_KEY,
    VersionBump,
    VersionHistoryUpdate,
    apply_version_bump,
    bump_for_export,
    bump_version,
    version_history_entry,
)
from .yaml_codec import (
    dump_document,
    dump_plugin_spec,
    load_document,
    load_plugin_spec,
)

__all__ = [
    "AtomicResult",
    "AtomicState",
    "atomic_apply",
    "try_atomic_apply",
    "Component",
    "FieldSchema",
    "FileTreeDiff",
    "PluginSpec",
    "SemVer",
    "PLUGIN_SPEC_SCHEMA",
    "SpecValidationError",
    "SpecValidator",
    "ValidationReport",
    "validate_spec",
    "SessionTokenAccount",
    "TokenInvocation",
    "sum_successful_tokens",
    "BreakingChangeResult",
    "classify_change",
    "is_breaking_change",
    "AUTHORIZED",
    "BUDGET_REACHED",
    "CostController",
    "Decision",
    "RATE_LIMITED",
    "RATE_LIMIT_WINDOW_SECONDS",
    "DocumentationError",
    "MissingMetadataError",
    "REQUIRED_METADATA_FIELDS",
    "generate_help",
    "write_help",
    "ComponentKind",
    "Draft",
    "DraftError",
    "ComponentNotFoundError",
    "ComponentExistsError",
    "ArtifactKind",
    "Classification",
    "DETERMINISTIC_ARTIFACT_KINDS",
    "GenerationRequest",
    "REASONING_ARTIFACT_KINDS",
    "REQUESTABLE_ARTIFACT_KINDS",
    "Route",
    "Template",
    "TemplateError",
    "TemplateLibrary",
    "classify_request",
    "default_template_library",
    "InputRejectionReason",
    "InputValidationResult",
    "MAX_INPUT_LENGTH",
    "MIN_INPUT_LENGTH",
    "is_acceptable_length",
    "is_blank",
    "validate_conversation_input",
    "CUSTOM_VENDOR_SUFFIX",
    "apply_custom_vendor_suffix",
    "BUMP_MAJOR",
    "BUMP_NONE",
    "BUMP_PATCH",
    "VERSION_HISTORY_KEY",
    "VersionBump",
    "VersionHistoryUpdate",
    "apply_version_bump",
    "bump_for_export",
    "bump_version",
    "version_history_entry",
    "LimitOutOfRangeError",
    "RATE_LIMIT_MAX",
    "RATE_LIMIT_MIN",
    "TOKEN_BUDGET_MAX",
    "TOKEN_BUDGET_MIN",
    "is_valid_rate_limit",
    "is_valid_token_budget",
    "validate_rate_limit",
    "validate_token_budget",
    "MAX_DISPLAY_CHARS",
    "TruncatedOutput",
    "truncate_error_output",
    "ACTION",
    "CONNECTION",
    "TASK",
    "TRIGGER",
    "FieldView",
    "NodeView",
    "NodeNotFoundError",
    "VisualizationViewModel",
    "build_view_model",
    "EMPTY_STATE_MESSAGE",
    "VisualizationRender",
    "VisualizationRenderer",
    "VisualizationState",
    "render_visualization",
    "diff_file_trees",
    "MASK_PLACEHOLDER",
    "mask_secret",
    "redact_secret",
    "redact_secrets",
    "dump_document",
    "dump_plugin_spec",
    "load_document",
    "load_plugin_spec",
]
