"""Which files in a plugin working tree are generated, lintable, and packaged.

Three predicates over relative paths, kept in one place because three subsystems
have to agree about them and previously did not: the ``Quality_Gate`` decides
which findings are actionable, the ``Code_Validator``'s ``lint`` stage decides
which files to judge, and the ``Build_Engine`` decides what goes into the ``.plg``.
When each answered the question for itself, a plugin could be told its code was
unclean on the strength of files its author is forbidden to edit.

They are deliberately three predicates rather than one, because they mean
different things:

* :func:`is_generated` -- emitted by the ``Insight_Plugin_CLI`` from the spec. The
  ``Agent_Rulebook`` forbids editing these and ``insight-plugin refresh`` would
  overwrite any edit, so a finding against one is not actionable. They are
  **still packaged**: the plugin needs them to run.
* :func:`is_lint_excluded` -- everything generated, plus ``unit_test/``. Lint
  only. The unit tests are still compiled, still format-checked, and still run;
  it is the linter alone that skips them, as the plugins repository's own
  static-analysis job does.
* :func:`is_packaging_excluded` -- the tool's own ``.builder/`` metadata and
  transient version-control and cache directories. Nothing here reaches the
  artifact.

The exclusions are justified by what the excluded thing *is* -- generated by the
CLI, or not part of the plugin -- and never by its having produced a complaint.
The tradeoff, stated rather than hidden: a genuine defect inside a generated file
will not be reported by the lint and format checks, which is accepted because such
a defect is a defect in the CLI's templates and could not be fixed in the plugin.

Pure path logic with no I/O beyond :func:`hand_written_python`'s directory walk,
which is why this lives in ``core/`` beside the other pure predicates.
"""

from __future__ import annotations

from pathlib import Path, PurePosixPath
from typing import List, Tuple, Union

__all__ = [
    "GENERATED_FILE_NAMES",
    "GENERATED_DIR_NAMES",
    "PACKAGING_EXCLUDED_DIR_NAMES",
    "UNIT_TEST_DIR",
    "is_generated",
    "is_lint_excluded",
    "is_packaging_excluded",
    "hand_written_python",
]

#: Files ``insight-plugin`` generates from the spec. The steering forbids editing
#: them, so findings against them are not actionable and are dropped.
GENERATED_FILE_NAMES = frozenset(
    {
        "schema.py",
        "__init__.py",
        "setup.py",
        "Dockerfile",
        "Makefile",
        "help.md",
        ".CHECKSUM",
    }
)

#: Directories whose entire contents are generated or vendored.
GENERATED_DIR_NAMES = frozenset({"bin", ".builder", "build", "dist", "__pycache__", ".git"})

#: Directories that never reach the ``.plg``: the tool's own metadata subtree
#: (Req 14.3) and transient version-control and cache directories.
PACKAGING_EXCLUDED_DIR_NAMES = frozenset({".builder", ".git", "__pycache__", ".pytest_cache", ".mypy_cache"})

#: Where a plugin's unit tests live.
UNIT_TEST_DIR = "unit_test"


def is_generated(relative_path: Union[str, PurePosixPath]) -> bool:
    """Return ``True`` iff ``relative_path`` is a generated or vendored file.

    Findings against these are not actionable: the plugin steering forbids
    hand-editing them, and ``insight-plugin refresh`` would overwrite any edit.
    """
    parts = PurePosixPath(str(relative_path)).parts
    if any(part in GENERATED_DIR_NAMES for part in parts):
        return True
    return bool(parts) and parts[-1] in GENERATED_FILE_NAMES


def is_lint_excluded(relative_path: Union[str, PurePosixPath]) -> bool:
    """Return ``True`` iff ``relative_path`` is outside the linter's remit.

    Everything :func:`is_generated` covers, plus the unit tests. The plugins
    repository's own static-analysis job filters ``unit_test/`` out before running
    prospector, so a test that trips ``protected-access`` for mocking a private
    method is not a defect the plugin has to answer for.

    Deliberately *not* the same predicate as :func:`is_generated`: the unit tests
    are still compiled, still formatted, and still run. Only the linter skips them.
    """
    if is_generated(relative_path):
        return True
    parts = PurePosixPath(str(relative_path)).parts
    return UNIT_TEST_DIR in parts


def is_packaging_excluded(relative_path: Union[str, PurePosixPath]) -> bool:
    """Return ``True`` iff ``relative_path`` must not reach the ``.plg``.

    Deliberately *not* :func:`is_generated`: a generated ``schema.py`` or
    ``Dockerfile`` is excluded from lint and still packaged, because the plugin
    cannot run without it. Only the tool's own metadata and transient directories
    are dropped here.
    """
    parts = PurePosixPath(str(relative_path)).parts
    return any(part in PACKAGING_EXCLUDED_DIR_NAMES for part in parts)


def hand_written_python(project_dir: Union[str, Path]) -> Tuple[str, ...]:
    """Return the hand-written ``.py`` files under ``project_dir``, sorted.

    Paths are relative and POSIX-separated. Generated files are excluded per
    :func:`is_generated`.
    """
    root = Path(project_dir)
    if not root.is_dir():
        return ()
    found: List[str] = []
    for path in root.rglob("*.py"):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if is_generated(relative):
            continue
        found.append(relative)
    return tuple(sorted(found))
